<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageReadmeFile>docs/fake-readme.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProfilesApi.Domain\ProfilesApi.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Validation\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.2.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
      <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    </ItemGroup>

</Project>
